DROP TABLE IF EXISTS albulms;
DROP TABLE IF EXISTS artists;


CREATE TABLE artists(
  id SERIAL4 PRIMARY KEY,
  name VARCHAR(255)
);

CREATE TABLE albulms(
  id SERIAL8 PRIMARY KEY,
  title VARCHAR(255),
  genre VARCHAR(255)
  artist_id INT8 REFERENCES artists(id) #NEED REFRESH
);
